### ISSUE TITLE
Example should be renamed to include simpletest

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_miniesptool#12]
Example `miniesptool_esp32multifile.py` should be renamed to `miniesptool_esp32multifile_simpletest.py` to fit with CircuitPython library standards.

**Comment by jerryneedell** [comment]
In this case, the examples are really not "simple tests" they are used to load code to the esp32 module.  A user should not run this to "see how it works".  Is "simpletest" really the appropriate name?

**Comment by kattni** [comment]
@jerryneedell Perhaps not. I guessed. What would be considered a simpletest for this library?

**Comment by jerryneedell** [comment]
I'm not sure there really is one.  It would be like having a simpletest for a .uf2 file. If you run it , it will write the file to your board.

**Comment by kattni** [comment]
Fair enough. Closing this issue. I think we should consider figuring out what would be considered a simpletest for this lib though, if at all possible.

**Comment by jerryneedell** [comment]
perhaps @brentru would have some ideas -- this may fit into his guide for the esp32spi...
