### ISSUE TITLE
Library needs simpletest example

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_miniesptool#19]
This library has no simpletest example. This was discussed in #12 but it did not result in the addition of a simpletest. I'm opening a new issue to being this discussion up again.

@jerryneedell or @brentru Do you have any suggestions?

**Comment by brentru** [comment]
@kattni  The example which flashes nina-fw to an esp32 would be a good simpletest -> https://github.com/adafruit/Adafruit_CircuitPython_miniesptool/blob/master/examples/miniesptool_esp32nina.py

**Comment by kattni** [comment]
@brentru Thank you so much!

**Comment by kattni** [comment]
@brentru Would you suggest calling it `miniesptool_simpletest` or `miniesptool_esls32nina_simpletest` ?

**Comment by brentru** [comment]
@kattni  `miniesptool_simpletest` is OK
