### ISSUE TITLE
unable to sync with esp8266 via particle.xenon board

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_miniesptool#2]
The miniesptool_esp8266progam.py works on a feather_m4 connected to an esp8266breakout, but I am unable to get it to work with a particle.xenon (nrf52840) board. it fails the sync() test at the start.
I have not tested this on other nrf52840 boards yet.

**Comment by ladyada** [comment]
this has been solved too, i think! closing - re-open if its not fixed

**Comment by jerryneedell** [comment]
yes -- fixed!
