### ISSUE TITLE
I found an escape bug，at line 353 of the adafruit_miniesptool.py file

### ISSUE THREAD

**Issue by Vinx911** [adafruit/Adafruit_CircuitPython_miniesptool#24]
https://github.com/adafruit/Adafruit_CircuitPython_miniesptool/blob/c756294fbad3f37c6d936d36918df2f25f25a3cf/adafruit_miniesptool.py#L353

https://github.com/espressif/esptool/wiki/Serial-Protocol#low-level-protocol
Each SLIP packet begins and ends with 0xC0. Within the packet, all occurrences of 0xC0 and 0xDB are replaced with 0xDB 0xDC and 0xDB 0xDD, respectively. The replacing is to be done after the checksum and lengths are calculated, so the packet length may be longer than the size field below.

`reply += b"\xDC"`   ===>>  `reply += b"\xDB"`

**Comment by ladyada** [comment]
hi not sure exactly what you're referring to, can you submit a PR with your fix?

**Comment by makermelissa** [comment]
Fixed via #25.
