### ISSUE TITLE
OSError on large files

### ISSUE THREAD

**Issue by maholli** [adafruit/Adafruit_CircuitPython_miniesptool#9]
I've been using miniesptool with files on an SD card (too large for internal flash).

It usually works, but I've ran into:
```
Traceback (most recent call last):
  File "main.py", line 74, in <module>
  File "adafruit_miniesptool.py", line 423, in flash_file
  File "adafruit_miniesptool.py", line 410, in flash_file
OSError: [Errno 5] Input/output error
``` 
when the file is greater than ~1.5MB. The OSError: [Errno 5] appears to be generic. Line 410 where the error occurs is when CP tries to read file contents (after opening). 

I've found that reducing the `FLASH_WRITE_SIZE` from 0x400 to 0x200 on https://github.com/adafruit/Adafruit_CircuitPython_miniesptool/blob/0362c361f51ca529da7747f7cd09d094bb72a77b/adafruit_miniesptool.py#L104 resolves my issue. I also tried adding a gc.collect() prior to the file.read() call, but that didn't seem to help.

**Comment by ladyada** [comment]
@maholli yeah this is a bug in the SD card library but im ok fixing it here for now - can you submit a PR?

**Comment by dherrada** [comment]
@ladyada I'm not sure if this is still wanted, but since it was a really quick fix, I made a PR using the code that @maholli wrote.

**Comment by ladyada** [comment]
oh yeah that makes sense. thx!
